### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by markoj21** [csnover/TraceKit#28]
First let me say that i really enjoy using your library and thank you for the hard work.

Can you create a nuget package for this library?

Thanks.

**Comment by niemyjski** [comment]
I'd recommend using the bower or npm package. Microsoft is urging users to use bower or npm and is even including first class support for both inside of VS2013/2015. Have you considered using this?

**Comment by niemyjski** [comment]
@markoj21 does this work for you or do you think we should still create a nuget package? The downside of creating a nuget package is it's one more thing to do per release.

**Comment by niemyjski** [comment]
@markoj21 what are your thoughts?

**Comment by markoj21** [comment]
Hi thank you your input,

npm is a great alternative, with the projects i work with nuget is supported by most other packages making it very easy to update and stay current. Having multiple package managers adds extra complexity but maintaining multiple distribution channels makes releases more difficult. 
I think you can close this and put it under it would be nice to have :)

**Comment by niemyjski** [comment]
Thanks for the feedback!
