### ISSUE TITLE
The handlers are called twice when calling TraceKit.report 

### ISSUE THREAD

**Issue by dimmetrius** [csnover/TraceKit#32]
Hello!

I created a simple page to test TraceKit:
https://github.com/dimmetrius/TraceTest.git
and this page deployed to site:
http://tracekit.azurewebsites.net

Why do I have 2 error message?

**Comment by niemyjski** [comment]
That's a good question. Any chance you could debug into it and see how many times report is being called.

**Comment by dimmetrius** [comment]
function traceKitWindowOnError called after throw ex in line:255

**Comment by niemyjski** [comment]
I'll have to take a closer look, I'll use your sample when I get some free time..  Is there any chance you could take your small sample and merge it into our tests?

**Comment by dimmetrius** [comment]
it('it should not throw', function (done){

            var i = 0;

            function handler(stackInfo) {
                i++;
            }

            TraceKit.report.subscribe(handler);

            function test() {
                try {
                    a++;
                } catch (e) {
                    TraceKit.report(e);
                }
            }

            expect(test).not.toThrow();

            setTimeout(function () {
                expect(i).toBe(1);
                done();
            }, 1000);
        }, 2000);

**Comment by niemyjski** [comment]
Thanks, I'll add this to the tests this weekend and take a look. It's been kind of crazy here with travel the past two weeks

**Comment by niemyjski** [comment]
This weekend was crazy, I'll try my best to look into this very soon.

**Comment by niemyjski** [comment]
@dimmetrius, I just added your unit tests with a few tweaks but when I run `grunt test` I'm seeing

```
it should call report handler once......X
     Expected function not to throw, but it threw ReferenceError: Can't find variable: a. (1)
 Parser
```

Are you seeing this as well? I would of thought the assert would fail not the exception expect. Do you know if just calling TraceKit.Report(new Error()) causes this as well?

**Comment by niemyjski** [comment]
Seems the report is rethrowing the exception.. I'll have to step into this more. Thanks for the test.

**Comment by niemyjski** [comment]
@dimmetrius, so the last line of report rethrows the exception so the window.onerror can get the exception and we can get a fuller stack trace. This is stupid however as we already have the fully captured stack trace. I need to look into merging in some changes from #14 which will resolve this behavior.

**Comment by niemyjski** [comment]
@dimmetrius @devinrhode2, 

I did some looking into refactoring and cleaning up the report method. I'd like to get rid of all the window on error logic in there and cleanup reporting handlers.. I noticed this comment:

```js
/* Tries to catch all unhandled exceptions and report them to the
 * subscribed handlers. Please note that TraceKit.report will rethrow the
 * exception. This is REQUIRED in order to get a useful stack trace in IE.
 * If the exception does not reach the top of the browser, you will only
 * get a stack trace from the point where TraceKit.report was called.
 */
```

I'm thinking that maybe this was only for really old versions of IE (I'm not sure). I know this library tries to cover all browsers back to ie5.. But we could break compat and really cleanup this code at the expense at missing some info in old browsers.. I think this is acceptable, what do you think? I think report should just compute the stack from the passed in exception and call any handlers and that's it. Right now it's rethrowing and doing a bunch of `crap`.

**Comment by Lendar** [comment]
Hi there! I'm testing TraceKit with IE6. For the reference: I'm using [TraceKit from raven-js#1.1.22](https://github.com/getsentry/raven-js/blob/1.1.22/vendor/TraceKit/tracekit.js)

Seems that re-throw is helpful in IE6 and some other browsers.

> But we could break compat and really cleanup this code at the expense at missing some info in old browsers.. I think this is acceptable, what do you think? 

Not sure how I can test it. But currently I have full stack traces working in IE6 (i.e. TraceKit brings 10+ frames, all with line numbers and source code context).

So, if you could provide small patch I could apply it on top of RavenJS TraceKit and see how much info is lost in IE6 (and I guess, in IE7 and old Safari).

**Comment by niemyjski** [comment]
Is there any chance you could write out the stack trace before the throw and after so we can compare ?

Sent from Outlook




On Thu, Oct 8, 2015 at 8:14 AM -0700, "Denis Elistratov" <notifications@github.com> wrote:












Hi there! I'm testing TraceKit with IE6. For the reference: I'm using TraceKit from raven-js#1.1.22



Seems that re-throw is helpful in IE6 and some other browsers.




But we could break compat and really cleanup this code at the expense at missing some info in old browsers.. I think this is acceptable, what do you think? 




Not sure how I can test it. But currently I have full stack traces working in IE6 (i.e. TraceKit brings 10+ frames, all with line numbers and source code context).



So, if you could provide small patch I could apply it on top of RavenJS TraceKit and see how much info is lost in IE6 (and I guess, in IE7 and old Safari).

**Comment by dimmetrius** [comment]
You can make a special setting,
for example: TraceKit.oldIEcompatible = true;

But it makes little sense to fight for compatibility with old IE.
Beginning January 12, 2016, only the current version of Internet Explorer available for a supported operating system will receive technical support and security 
https://technet.microsoft.com/en-us/ie/mt163707

**Comment by niemyjski** [comment]
Well I'd try not to break anything. I just wonder what's all missing if we don't rethrow this info.. All I have is modern browsers. I'd need to set up an old xp vm or something and take a look.

**Comment by niemyjski** [comment]
What I'm curious is can you write out the raw original exception and then the trace that tracekit generates after rethrowing. So we can see the difference.

**Comment by Lendar** [comment]
@niemyjski tested that patch

```
diff --git a/src/vendor/raven.js b/src/vendor/raven.js
index 92caf4d..c3ef98d 100644
--- a/src/vendor/raven.js
+++ b/src/vendor/raven.js
@@ -258,9 +258,6 @@ TraceKit.report = (function reportModuleWrapper() {
             }
         }, (stack.incomplete ? 2000 : 0));
 
-        if (rethrow !== false) {
-            throw ex; // re-throw to propagate to the top level (and cause window.onerror)
-        }
     }
 
     report.subscribe = subscribe;
```

Then I compared stack traces using sentry.js. Everything was same except 1 last frame (which actually caused error) – it is gone.

**Comment by niemyjski** [comment]
So the top stack trace line is missing completely? Looks like I should pull down windows xp and setup a vm.

**Comment by niemyjski** [comment]
Can you verify if this is fixed with the latest release. If it's not can you comment and let me know and we will reopen this.
