### ISSUE TITLE
Support blob: URLs

### ISSUE THREAD

**Issue by pornel** [csnover/TraceKit#36]
`createObjectURL()` can be used to create a URL in format `blob:http://origin/uuid` that's very handy for [creating Web Workers](http://stackoverflow.com/a/10372280/27009) and we also create `<script>` elements with these Blob URLs as part of workarounds for appcache being appcache.

The problem is that TraceKit doesn't recognize `blob:` URLs, and therefore Sentry doesn't recognize them either, so we don't get backtraces in our error reports.

Could you add support for blob: URLs? 

If needed, our app would be able to provide mapping from blob: URLs to equivalent HTTP file URLs or return its content as a string.

**Comment by niemyjski** [comment]
Would you mind creating a pull request for this?
