### ISSUE TITLE
Difference between https://github.com/stacktracejs/stacktrace.js and TraceKit

### ISSUE THREAD

**Issue by rayqian** [csnover/TraceKit#38]
BTW: is there any chat rooms for exchange message?

**Comment by niemyjski** [comment]
I'm on gitter [here](https://gitter.im/exceptionless/Discuss) if you'd like to talk about it. 

There are a few differences to take note:
* TraceKit supports es3 browsers where StackTrace doesn't
* StackTrace doesn't parse some stack traces correctly (IE).
* StackTrace is a little more modular, something we are trying to do with plugins here (if you'd like to help that would be greatly appreciated).
