### ISSUE TITLE
Make it possible to alter `debug`

### ISSUE THREAD

**Issue by benvinegar** [csnover/TraceKit#40]
The `debug` variable is declared as a "private" variable inside `TraceKit.computeStackTrace`. It seems the only way to alter it is to edit the source code.

https://github.com/csnover/TraceKit/blob/master/tracekit.js#L319

Can we make this modifiable, say, via `TraceKit.debug`?

**Comment by niemyjski** [comment]
@benvinegar any specific reason for wanting this exposed? I guess for testing your own scripts? I think that we need to expose more things but stay out of property hell. If we have a good use case for this, lets expose it (can you submit a pr).

**Comment by niemyjski** [comment]
@benvinegar ^^

**Comment by benvinegar** [comment]
@niemyjski I think this was as a convenience. I didn't like that I needed to edit a file, rebundle Tracekit, in order to do some simple debugging.

>  stay out of property hell.

I wasn't aware this was a thing. I personally don't see a problem with exposing options as properties.

**Comment by niemyjski** [comment]
If you want to submit a pull request I'll accept it. I just thought that if you are debugging an issue you should be using unminified sources

**Comment by niemyjski** [comment]
@benvinegar would you mind submitting a pr for this.

**Comment by benvinegar** [comment]
@niemyjski I mean, I could, but at this point I no longer have need for the flag and nobody else has commented or +1'd this.
