### ISSUE TITLE
Firefox trace isn't parsed correctly

### ISSUE THREAD

**Issue by thomasbachem** [csnover/TraceKit#42]
Firefox 43 has stack strings like these:

```
Module.fooFunc/<@https://example.com/foo.js:531:5
Module.fooFunc@https://example.com/foo.js:530:5
Module.barFunc/<@https://example.com/foo.js:40:6
aspect/</dispatcher@https://example.com/vendor/dojotoolkit/dojo/aspect.js:98:25
Module.bazFunc/liNode.onclick@https://example.com/foo.js:444:10
```

The `<` seems to indicate anonymous functions, but I have no idea where exactly the `dispatcher` thing comes from. You can maybe look into [Dojo's aspect.js](https://github.com/dojo/dojo/blob/1.10/aspect.js) to understand Firefox' behavior here.

Also I'm not sure whether the `Function()`/`eval()` stuff [documented at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack) (Firefox 30+) is supported, as the pattern doesn't look like it does. Example from MDN:

```
@file:///C:/example.html line 7 > eval line 1 > eval:1:1
@file:///C:/example.html line 7 > eval:1:1
@file:///C:/example.html:7:6
```

**Comment by niemyjski** [comment]
@thomasbachem any chance you could add this case to the unit tests and update the code for this. I'll then push a new release.

**Comment by niemyjski** [comment]
@thomasbachem were you able to look into this further?

**Comment by niemyjski** [comment]
@thomasbachem I think this may be fixed in the latest release that I just published. Can you please verify this.

**Comment by niemyjski** [comment]
@thomasbachem were you able to confirm if this was fixed?

**Comment by auchenberg** [comment]
You might wanna take a look at this package, https://www.npmjs.com/package/error-stack-normalizer

**Comment by niemyjski** [comment]
@auchenberg I've taken a look at it, we actually do quite a few things better than them, but currently they are more modular...

**Comment by auchenberg** [comment]
@niemyjski Yeah, but this is a simply "normalizer" that's 100% separate that I wrote. You could consider use and contribute to the normalization logic instead of putting everything inside TraceKit :)

**Comment by niemyjski** [comment]
Yes, but it requires buy in to a module loader and doesn't work with older browsers (es3 or lower)

**Comment by niemyjski** [comment]
Let alone it doesn't correctly parse ie stack traces because ie is lame and doesn't always include the top stack frame

**Comment by niemyjski** [comment]
I believe this is fixed in the following issue & pr (https://github.com/csnover/TraceKit/issues/49)

@benvinegar can you confirm? This looks like the same issue. I'll work on getting a release out in the next day or two unless someone needs it asap.

Please reopen this issue if it's not fixed.
