### ISSUE TITLE
Update docs for TypeScript

### ISSUE THREAD

**Issue by dylanvdmerwe** [csnover/TraceKit#51]
There really should be some information on how to use this lib through npm and TypeScript. 

I'm trying to get this to work in an Angular 2 based project with not much luck.

**Comment by dylanvdmerwe** [comment]
`npm install tracekit --save`

`import * as tracekit from 'tracekit';`

Does not work.

**Comment by niemyjski** [comment]
@dylanvdmerwe I have a sample app here but I'm not using it through npm.

https://github.com/exceptionless/Exceptionless.JavaScript/tree/master/src

I have the typescript def copied to the typings directory and it would be a lot better if I didn't have this. Would you be willing to push the updated def to the  tsd directory (with all the other typescript definitions)? 

I put the definition in our tsconfig file: https://github.com/exceptionless/Exceptionless.JavaScript/blob/45babdff21b2adbd49d1404712d853cfb6fe4f21/src/tsconfig.json#L12 and I didn't have to import it but I probably should... https://github.com/exceptionless/Exceptionless.JavaScript/blob/45babdff21b2adbd49d1404712d853cfb6fe4f21/src/services/DefaultErrorParser.ts

Would you mind looking into this more? I'd be more than happy to meet up with you via a remote meeting and pair on this if you want.

**Comment by niemyjski** [comment]
I just pushed a new version of typescript which fixes the npm typescript typings. They should now be automatically be pulled in.

**Comment by dylanvdmerwe** [comment]
I'm still trying to figure out TypeScript and how to get everything to work from a JavaScript world. 

Basically I'm trying to get TraceKit to work in an Ionic 2 project which is built on Angular 2 and TS. I have installed the new npm module, but no matter what I do, I cannot get a reference to TraceKit in order to use the report methods.

**Comment by niemyjski** [comment]
Can you create a public repo with a very simple project using (local dependencies like ionic) and I'll pull it down and take a look. Please include the code and imports where you are getting stuck.

**Comment by dylanvdmerwe** [comment]
See https://github.com/dylanvdmerwe/ionic-tracekit.

Once you grab the repo, go to the folder:
```
npm install -g ionic@beta
npm install
ionic serve
```

**Comment by niemyjski** [comment]
This should be fixed according to the master branch. Can you grab the latest master change and see if it fixes it.

**Comment by dylanvdmerwe** [comment]
That resolves the intellisense issue which is great. However the lib does not work during runtime. 

![capture](https://cloud.githubusercontent.com/assets/2852839/14332049/2aee31c0-fc48-11e5-98f3-66a7277d5b59.jpg)

**Comment by niemyjski** [comment]
So this is only the ambient typing that is being brought in. I don't see where you are actually referencing the tracekit javascript file and bringing it in as a dependency.

**Comment by dylanvdmerwe** [comment]
No you cannot just reference the js. Everything is built and bundled into a singular javascript file and as such there would be nowhere to reference this.

For example, when I npm install lodash, I do not have to reference the various js files in the project.

Doesn't the js file need to have module exports?

**Comment by niemyjski** [comment]
Did the exports fix it completely? If so, I think we need to move to a standardized umd pattern:

```js
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(factory);
  } else if (typeof exports === 'object') {
    module.exports = factory(require, exports, module);
  } else {
    root.exceptionless = factory();
  }
}(this, function(require, exports, module) {
if (!exports) {
	var exports = {};
}
```

I've been using typescript in my own project and concatted tracekit to our builds. I don't get how having an exports helps here because you are referencing the ambient definition (tracekit.d.ts) for intellisense which doesn't do anything for the actual file import.

**Comment by frankebersoll** [comment]
I didn't see this issue (and PR #54) and added pull request #53 for this yesterday. Now you should be able to install it with npm and just import it like this:

`import * as TraceKit from 'tracekit'`

**Comment by niemyjski** [comment]
@dylanvdmerwe were you able to get this to work with the latest release?

**Comment by dylanvdmerwe** [comment]
With the changes I made as per my pull request I was able to get this working yes.

**Comment by niemyjski** [comment]
@dylanvdmerwe would you look into updating your pr to support umd pattern. I'm not willing to accept your pr as is as I know for 100% that it will break anyone not using amd / module loader.

**Comment by niemyjski** [comment]
@dylanvdmerwe I've done extensive testing (4 hours) and I've think I've fixed a number of bugs that were dealing with typescript and es6. I've created a new release (https://github.com/csnover/TraceKit/releases/tag/v0.4.0) with more info on typescript usage.  Is there any chance you want to fork `typings/repository` and link to our definitions?
