### ISSUE TITLE
Module loading code throws errors in strict mode

### ISSUE THREAD

**Issue by rgossiaux** [csnover/TraceKit#61]
In the check `if (typeof module !== 'undefined' && module.exports && this.module !== module)` the `this.module` part fails in strict mode, where `this` is undefined. Since this check is intended to determine if the `module` in scope is coming from the global scope, replacing with `window.module` gives the correct behavior.

**Comment by niemyjski** [comment]
Thanks for this fix. I'll try putting out a release soon.
