### ISSUE TITLE
`repors.subscribe` subscribers have no access to the original Error object

### ISSUE THREAD

**Issue by futpib** [csnover/TraceKit#66]
Access to the original `Error` instance is needed if your errors may contain additional debug info, for example, fetch `Request`, like [github/fetch suggests](https://github.com/github/fetch/blob/df0f332/README.md#handling-http-error-statuses).

One may want to try to get some info from `error.request` before submitting error report to server.

**Comment by niemyjski** [comment]
Yeah, I just noticed that when you pointed it out. The only non breaking change here would be if we added a third param to  the handlers (https://github.com/csnover/TraceKit/blob/master/tracekit.js#L160). Would you mind submitting a pr with a unit test for this and I'll accept it and get a new release out asap.

**Comment by futpib** [comment]
Awesome, will do.

**Comment by niemyjski** [comment]
Do you need a release out for this right away?

**Comment by futpib** [comment]
Not really, I managed to monkey-path this in before reporting >_<
Appreciate your involvement though
