### ISSUE TITLE
Wipes `url` property from stack if url contains "native"

### ISSUE THREAD

**Issue by benvinegar** [csnover/TraceKit#69]
[This line:](https://github.com/csnover/TraceKit/blob/master/tracekit.js#L716)

```
var isNative = parts[2] && parts[2].indexOf('native') !== -1;
```

... is trying to determine whether the "URL" part is `[native code]` (etc), but fails if any part of a real URL contains the string `"native"`, e.g. `https://example.com/static/js/lib/native.js`.

**Comment by niemyjski** [comment]
Nice find, any chance you can submit a test + patch for this and I'll get it merged in asap.
