### ISSUE TITLE
Unable to set remoteFetching in TypeScript

### ISSUE THREAD

**Issue by mlynch** [csnover/TraceKit#71]
The way `remoteFetching` is defined and exported makes it (nearly?) impossible to modify in a TypeScript context.

This example causes a TS error:

```typescript
import * as TraceKit from 'tracekit';

TraceKit.remoteFetching = false;
```

And the error:

```
semantic error TS2540 Cannot assign to 'remoteFetching' because it is a constant or a read-only property.
```

I've tried to trick typescript into allowing modification of this by assigning it to another variable but its properties have had `Object.preventExtensions` marked on them, which I'm guessing is part of the module import contract. 

Thanks for a great library!

**Comment by niemyjski** [comment]
I don't see `Object.preventExtensions` used anywhere in our entire codebase. Would you mind taking a closer look into this and submit a pr. I'm not sure of anything that would be causing this.

**Comment by nponiros** [comment]
ECMAScript module imports are read-only. So `TraceKit.remoteFetching = false;` is not allowed by the spec and TypeScript seems to be enforcing this. Executing the code in a browser with ECMAScript module support would also fail.

This will probably work:

```
import TraceKit from 'tracekit';

TraceKit.remoteFetching = false;
```

**Comment by niemyjski** [comment]
Thanks for the clarification! If there still is an issue here please let us know.
