### ISSUE TITLE
Catch unhandled promise rejection events

### ISSUE THREAD

**Issue by jh3141** [csnover/TraceKit#72]
Promise rejection events can be caught via the [`window.onunhandledrejection` event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection).  If an exception is thrown during processing of a Promise (either during its initial execution phase or during processing a "then" function attached to it), the Promise is rejected and the "`reason`" entry in the rejection event will be an `Error`.  `reason` may also be any other type, as it will be populated with whatever argument is given in calls to the `reject` function of the Promise handler, so will need to be checked before handling.  I'm not sure how TraceKit should behave if it catches an unhandled rejection that is not an `Error`.

Support for this feature of Promises isn't great yet, but is improving (see http://caniuse.com/#feat=unhandledrejection).

**Comment by niemyjski** [comment]
Can you submit a pr for this?

**Comment by niemyjski** [comment]
@jh3141 can you submit a pr for this

**Comment by ghostd** [comment]
Here is a PR: #73

**Comment by ghostd** [comment]
Hi @niemyjski 

Can we close this issue and bump the version please? I'd like to update my deps with a version handling the promises.

Thx

**Comment by niemyjski** [comment]
@ghostd yes, I'll cut a release. I was just trying to get https://github.com/csnover/TraceKit/pull/68 merged in as well.

**Comment by niemyjski** [comment]
Could you please review this as well

**Comment by adams-family** [comment]
I confirm that 'Possible unhandled rejections' are still not being caught at this moment. Is there a workaround for this? Thanks.

**Comment by niemyjski** [comment]
I was under the impression that this has been fixed. Can you please add
some tests or send us a demo that fails and let us know under which browser
it fails.
Thanks
-Blake Niemyjski

**Comment by adams-family** [comment]
Hi Blake,
Sorry for the late answer, I managed to create a demo of my issue.
Just open `index.html` and look at the F12 console. You'll see a Possible unhandled rejection not being caught by Tracekit.
Maybe it's beacuse of something stupid but it wasn't able to figure it out.
Thanks, Adam

[Demo.zip](https://github.com/csnover/TraceKit/files/3611573/Demo.zip)

**Comment by erikdubbelboer** [comment]
Since this has been merged is there any plan to tag a new release?

**Comment by niemyjski** [comment]
I've pushed this in a release, sorry for the delay: https://github.com/csnover/TraceKit/releases/tag/v0.4.6
