### ISSUE TITLE
TraceKit Unhandled Promise Rejection 0.4.6 not yet published in NPM

### ISSUE THREAD

**Issue by acaballes** [csnover/TraceKit#83]
HI, the release for this issue https://github.com/csnover/TraceKit/releases/tag/v0.4.6 here is not yet published in the npm package https://www.npmjs.com/package/tracekit. still 0.4.5.

Can we please published it also in the npm?

Thanks,
Algie

**Comment by niemyjski** [comment]
Thanks for opening an issue for this. I thought I had this automated... I've just pushed this release out there.
